{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbba178d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Ship Routing and Dual-Color Movement Visualization with Static Red Trails and Animated Dots ---\n",
    "\n",
    "import geopandas as gpd\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from shapely.geometry import Point, LineString\n",
    "from shapely.ops import split, linemerge, unary_union\n",
    "from datetime import timedelta\n",
    "import folium\n",
    "from folium.plugins import TimestampedGeoJson\n",
    "import networkx as nx\n",
    "from sklearn.neighbors import BallTree\n",
    "from shapely.strtree import STRtree\n",
    "\n",
    "KNOT_TO_KMPH = 1.852\n",
    "\n",
    "# --- Load Data ---\n",
    "arrival_df = pd.read_excel(r\"C:\\Users\\Elian\\OneDrive - University of Puerto Rico\\Desktop\\CETL\\CODE\\VIS_DATA_IMP_COORD.xlsx\")\n",
    "departure_df = pd.read_excel(r\"C:\\Users\\Elian\\OneDrive - University of Puerto Rico\\Desktop\\CETL\\CODE\\VIS_DATA_EXP_COORD.xlsx\")\n",
    "arrival_df['ECDATE'] = pd.to_datetime(arrival_df['ECDATE'])\n",
    "departure_df['EBDATE'] = pd.to_datetime(departure_df['EBDATE'])\n",
    "combined_routes_gdf = gpd.read_file(r\"C:\\Users\\Elian\\OneDrive - University of Puerto Rico\\Desktop\\CETL\\CODE\\Combined_Routes.geojson\").to_crs(epsg=3857)\n",
    "\n",
    "# --- Geometry to Graph ---\n",
    "all_lines = []\n",
    "for _, row in combined_routes_gdf.iterrows():\n",
    "    geom = row.geometry\n",
    "    if geom.geom_type == 'MultiLineString':\n",
    "        all_lines.extend(list(geom.geoms))\n",
    "    elif geom.geom_type == 'LineString':\n",
    "        all_lines.append(geom)\n",
    "\n",
    "merged_lines = unary_union(all_lines)\n",
    "intersection_points = []\n",
    "for i, line1 in enumerate(all_lines):\n",
    "    for j in range(i + 1, len(all_lines)):\n",
    "        line2 = all_lines[j]\n",
    "        if line1.intersects(line2):\n",
    "            inter = line1.intersection(line2)\n",
    "            if inter.geom_type == 'Point':\n",
    "                intersection_points.append(inter)\n",
    "            elif inter.geom_type == 'MultiPoint':\n",
    "                intersection_points.extend(inter.geoms)\n",
    "\n",
    "def round_point(pt, precision=2):\n",
    "    return (round(pt.x, precision), round(pt.y, precision))\n",
    "\n",
    "unique_points = list({round_point(pt): pt for pt in intersection_points}.values())\n",
    "intersection_buffers = [pt.buffer(10) for pt in unique_points]\n",
    "split_lines = []\n",
    "\n",
    "for line in all_lines:\n",
    "    try:\n",
    "        tree = STRtree(intersection_buffers)\n",
    "        hits = tree.query(line)\n",
    "        splitters = [intersection_buffers[i] for i in hits if intersection_buffers[i].intersects(line) and not intersection_buffers[i].touches(line.boundary)]\n",
    "        result = line\n",
    "        for splitter in splitters:\n",
    "            try:\n",
    "                result = split(result, splitter)\n",
    "                if result.geom_type == 'GeometryCollection':\n",
    "                    result = linemerge([g for g in result.geoms if g.geom_type == 'LineString'])\n",
    "            except Exception as e:\n",
    "                print(f\"Failed split: {e}\")\n",
    "        if result.geom_type == 'MultiLineString':\n",
    "            split_lines.extend(result.geoms)\n",
    "        elif result.geom_type == 'LineString':\n",
    "            split_lines.append(result)\n",
    "    except Exception as e:\n",
    "        print(f\"Error during STRtree split: {e}\")\n",
    "\n",
    "# --- Network Graph ---\n",
    "G = nx.Graph()\n",
    "for line in split_lines:\n",
    "    coords = list(line.coords)\n",
    "    for i in range(len(coords) - 1):\n",
    "        u = coords[i]\n",
    "        v = coords[i + 1]\n",
    "        dist = LineString([u, v]).length\n",
    "        G.add_edge(u, v, weight=dist)\n",
    "\n",
    "nodes = np.array(G.nodes)\n",
    "tree = BallTree(nodes, metric='euclidean')\n",
    "indices = tree.query_radius(nodes, r=10000)\n",
    "for i, neighbors in enumerate(indices):\n",
    "    u = tuple(nodes[i])\n",
    "    for j in neighbors:\n",
    "        if i >= j:\n",
    "            continue\n",
    "        v = tuple(nodes[j])\n",
    "        if not G.has_edge(u, v):\n",
    "            dist = np.linalg.norm(nodes[i] - nodes[j])\n",
    "            G.add_edge(u, v, weight=dist)\n",
    "\n",
    "endpoint_nodes = []\n",
    "for line in split_lines:\n",
    "    coords = list(line.coords)\n",
    "    endpoint_nodes.append(coords[0])\n",
    "    endpoint_nodes.append(coords[-1])\n",
    "\n",
    "endpoint_array = np.array(endpoint_nodes)\n",
    "endpoint_tree = BallTree(endpoint_array, metric='euclidean')\n",
    "nearby_pairs = endpoint_tree.query_radius(endpoint_array, r=1000)\n",
    "for i, neighbors in enumerate(nearby_pairs):\n",
    "    u = tuple(endpoint_array[i])\n",
    "    for j in neighbors:\n",
    "        if i >= j:\n",
    "            continue\n",
    "        v = tuple(endpoint_array[j])\n",
    "        if not G.has_edge(u, v):\n",
    "            dist = np.linalg.norm(endpoint_array[i] - endpoint_array[j])\n",
    "            G.add_edge(u, v, weight=dist)\n",
    "\n",
    "# --- Route Calculation and Ship Path Interpolation ---\n",
    "def get_route_coords(origin_proj, dest_proj):\n",
    "    origin_pt = (origin_proj.x, origin_proj.y)\n",
    "    dest_pt = (dest_proj.x, dest_proj.y)\n",
    "    tempG = G.copy()\n",
    "    tempG.add_node(origin_pt)\n",
    "    tempG.add_node(dest_pt)\n",
    "    node_coords = np.array(list(G.nodes))\n",
    "    origin_tree = BallTree(node_coords, metric='euclidean')\n",
    "    _, origin_idx = origin_tree.query([origin_pt], k=1)\n",
    "    nearest_origin = tuple(node_coords[origin_idx[0][0]])\n",
    "    _, dest_idx = origin_tree.query([dest_pt], k=1)\n",
    "    nearest_dest = tuple(node_coords[dest_idx[0][0]])\n",
    "    tempG.add_edge(origin_pt, nearest_origin, weight=Point(origin_pt).distance(Point(nearest_origin)))\n",
    "    tempG.add_edge(dest_pt, nearest_dest, weight=Point(dest_pt).distance(Point(nearest_dest)))\n",
    "    try:\n",
    "        path = nx.shortest_path(tempG, origin_pt, dest_pt, weight='weight')\n",
    "        return path\n",
    "    except nx.NetworkXNoPath:\n",
    "        return []\n",
    "\n",
    "def interpolate_path(coords, departure, arrival, row):\n",
    "    if len(coords) < 2:\n",
    "        return pd.DataFrame()\n",
    "    total_length = sum(LineString([coords[i], coords[i + 1]]).length for i in range(len(coords) - 1))\n",
    "    speed_mps = row['speed'] * KNOT_TO_KMPH * 1000 / 3600\n",
    "    total_seconds = total_length / speed_mps\n",
    "    steps = max(int(np.ceil(total_seconds / 3600)), 1)\n",
    "    times = pd.date_range(departure, arrival, periods=steps)\n",
    "    distances = np.linspace(0, total_length, steps)\n",
    "    line = LineString(coords)\n",
    "    points = [line.interpolate(d) for d in distances]\n",
    "    points_wgs84 = gpd.GeoSeries(points, crs='EPSG:3857').to_crs(epsg=4326)\n",
    "    return pd.DataFrame({\n",
    "        'VESSNAME': row['VESSNAME'],\n",
    "        'date': times,\n",
    "        'latitude': points_wgs84.y,\n",
    "        'longitude': points_wgs84.x,\n",
    "        'ICST_DESC': row['ICST_DESC'],\n",
    "        'ECDATE': arrival\n",
    "    })\n",
    "\n",
    "records = []\n",
    "route_cache = {}\n",
    "used_coords = []\n",
    "\n",
    "for source_type, df, time_col in [('arrival', arrival_df, 'ECDATE'), ('departure', departure_df, 'EBDATE')]:\n",
    "    for _, row in df.iterrows():\n",
    "        vess_name = str(row['VESSNAME']).strip()\n",
    "        print(f\"🔄 Calculating route for ship '{vess_name}' ({source_type})...\")\n",
    "        vess_name = str(row['VESSNAME']).strip()\n",
    "\n",
    "        if pd.isna(row['O LATITUDE']) or pd.isna(row['D LATITUDE']) or pd.isna(row['speed']) or row['speed'] <= 0:\n",
    "            continue\n",
    "\n",
    "        origin = Point(row['O LONGITUDE'], row['O LATITUDE'])\n",
    "        dest = Point(row['D LONGITUDE'], row['D LATITUDE'])\n",
    "        origin_proj = gpd.GeoSeries([origin], crs='EPSG:4326').to_crs(epsg=3857).iloc[0]\n",
    "        dest_proj = gpd.GeoSeries([dest], crs='EPSG:4326').to_crs(epsg=3857).iloc[0]\n",
    "\n",
    "        origin_key = (round(origin_proj.x, 3), round(origin_proj.y, 3))\n",
    "        dest_key = (round(dest_proj.x, 3), round(dest_proj.y, 3))\n",
    "        route_key = (origin_key, dest_key)\n",
    "\n",
    "        if route_key in route_cache:\n",
    "            coords = route_cache[route_key]\n",
    "        else:\n",
    "            coords = get_route_coords(origin_proj, dest_proj)\n",
    "            if coords and len(coords) >= 2:\n",
    "                route_cache[route_key] = coords\n",
    "\n",
    "        if not coords or len(coords) < 2:\n",
    "            continue\n",
    "\n",
    "        used_coords.append(LineString(coords))\n",
    "        dist_m = LineString(coords).length\n",
    "\n",
    "        speed_mps = row['speed'] * KNOT_TO_KMPH * 1000 / 3600\n",
    "        travel_seconds = dist_m / speed_mps\n",
    "\n",
    "        if source_type == 'arrival':\n",
    "            departure = row[time_col] - timedelta(seconds=travel_seconds)\n",
    "            path_df = interpolate_path(coords, departure, row[time_col], row)\n",
    "        else:\n",
    "            arrival = row[time_col] + timedelta(seconds=travel_seconds)\n",
    "            path_df = interpolate_path(coords, row[time_col], arrival, row)\n",
    "\n",
    "        path_df['source'] = source_type\n",
    "        records.append(path_df)\n",
    "\n",
    "all_ships = pd.concat(records, ignore_index=True) if records else pd.DataFrame()\n",
    "all_ships['date'] = pd.to_datetime(all_ships['date'])\n",
    "all_ships = all_ships[all_ships['date'] <= all_ships['ECDATE']]\n",
    "\n",
    "# --- Ship Type Grouping and Colors ---\n",
    "\n",
    "ship_type_to_group = {\n",
    "    # Container\n",
    "    \"CONTAINER\": \"Container\",\n",
    "    \"RO-RO CONTAINER\": \"Container\",\n",
    "\n",
    "    # Tankers\n",
    "    \"CHEMICAL TANKER\": \"Tanker\",\n",
    "    \"CRUDE OIL TANKER\": \"Tanker\",\n",
    "    \"CRUDE/PRODUCTS TANKER\": \"Tanker\",\n",
    "    \"OIL PRODUCTS TANKER\": \"Tanker\",\n",
    "    \"OTHER TANKER\": \"Tanker\",\n",
    "    \"OTHER TANKER NEI\": \"Tanker\",\n",
    "\n",
    "    # Bulk Carrier\n",
    "    \"OTHER BULK CARRIER\": \"Bulk Carrier\",\n",
    "    \"OTHER BULK/OIL CARRIER\": \"Bulk Carrier\",\n",
    "\n",
    "    # General Cargo\n",
    "    \"GENERAL CARGO-MULTI DECK NEI\": \"General Cargo\",\n",
    "    \"OTHER GENERAL CARGO\": \"General Cargo\",\n",
    "\n",
    "    # RoRo\n",
    "    \"RO-RO PASSENGER\": \"RoRo\",\n",
    "    \"OTHER RO-RO CARGO\": \"RoRo\",\n",
    "\n",
    "    # Passenger / Cruise\n",
    "    \"CRUISE\": \"Passenger / Cruise\",\n",
    "    \"OTHER PASSENGER\": \"Passenger / Cruise\",\n",
    "\n",
    "    # Barges & Support\n",
    "    \"DECK BARGE\": \"Barges & Support\",\n",
    "    \"DRY CARGO BARGE\": \"Barges & Support\",\n",
    "    \"OTHER DRY CARGO BARGE NEI\": \"Barges & Support\",\n",
    "    \"OTHER TANK BARGE\": \"Barges & Support\",\n",
    "    \"DREDGER\": \"Barges & Support\",\n",
    "    \"TUG\": \"Barges & Support\",\n",
    "    \"TUG/SUPPLY OFFSHORE SUPPORT\": \"Barges & Support\",\n",
    "    \"OTHER OFFSHORE PRODUCTION & SUPPORT\": \"Barges & Support\",\n",
    "\n",
    "    # Specialized / Other\n",
    "    \"DRILLING SHIP\": \"Specialized / Other\",\n",
    "    \"FISH CATCHING\": \"Specialized / Other\",\n",
    "    \"FISH PROCESSING\": \"Specialized / Other\",\n",
    "    \"LIVESTOCK CARRIER\": \"Specialized / Other\",\n",
    "    \"LNG CARRIER\": \"Specialized / Other\",\n",
    "    \"LPG CARRIER\": \"Specialized / Other\",\n",
    "    \"OTHER LIQUIFIED GAS CARRIER\": \"Specialized / Other\",\n",
    "    \"OTHER SPECIALIZED CARRIER NEI\": \"Specialized / Other\",\n",
    "    \"PUSH BOAT\": \"Specialized / Other\",\n",
    "    \"REEFER\": \"Specialized / Other\",\n",
    "    \"RESEARCH/SURVEY\": \"Specialized / Other\",\n",
    "    \"OTHER NEI\": \"Specialized / Other\",\n",
    "    \"OTHER LAKERS\": \"Specialized / Other\",\n",
    "    \"VEHICLE CARRIER\": \"Specialized / Other\",\n",
    "}\n",
    "\n",
    "group_fill_colors = {\n",
    "    \"Container\": \"#1f77b4\",\n",
    "    \"Tanker\": \"#ff7f0e\",\n",
    "    \"Bulk Carrier\": \"#2ca02c\",\n",
    "    \"General Cargo\": \"#d62728\",\n",
    "    \"RoRo\": \"#9467bd\",\n",
    "    \"Passenger / Cruise\": \"#e377c2\",\n",
    "    \"Barges & Support\": \"#8c564b\",\n",
    "    \"Specialized / Other\": \"#7f7f7f\",\n",
    "}\n",
    "\n",
    "def get_fill_color(ship_type):\n",
    "    group = ship_type_to_group.get(str(ship_type).upper(), \"Specialized / Other\")\n",
    "    return group_fill_colors.get(group, \"#7f7f7f\")\n",
    "\n",
    "def get_outline_color(source):\n",
    "    return 'red' if source == 'arrival' else 'blue'\n",
    "\n",
    "# --- Map Visualization ---\n",
    "m = folium.Map(location=[18.2, -66.5], zoom_start=6, tiles='CartoDB Positron')\n",
    "\n",
    "# Draw gray static routes\n",
    "for segment in split_lines:\n",
    "    seg_wgs84 = gpd.GeoSeries([segment], crs='EPSG:3857').to_crs(epsg=4326).iloc[0]\n",
    "    coords = [(lat, lon) for lon, lat in seg_wgs84.coords]\n",
    "    folium.PolyLine(coords, color='gray', weight=2, opacity=0.3).add_to(m)\n",
    "\n",
    "# Draw static trails based on unique cached routes\n",
    "plotted_trails = set()\n",
    "for coords in route_cache.values():\n",
    "    if len(coords) >= 2:\n",
    "        key = tuple(map(tuple, coords))\n",
    "        if key not in plotted_trails:\n",
    "            trail_line = LineString(coords)\n",
    "            trail_wgs84 = gpd.GeoSeries([trail_line], crs='EPSG:3857').to_crs(epsg=4326).iloc[0]\n",
    "            trail_coords = [(pt[1], pt[0]) for pt in trail_wgs84.coords]  # (lat, lon)\n",
    "            folium.PolyLine(trail_coords, color='purple', weight=3, opacity=0.8).add_to(m)\n",
    "            plotted_trails.add(key)\n",
    "\n",
    "# --- Animate ship dots ---\n",
    "features = []\n",
    "for _, row in all_ships.iterrows():\n",
    "    current_time = row['date'].strftime('%Y-%m-%dT%H:%M:%SZ')\n",
    "    coord = [row['longitude'], row['latitude']]\n",
    "    point_feature = {\n",
    "        'type': 'Feature',\n",
    "        'geometry': {'type': 'Point', 'coordinates': coord},\n",
    "        'properties': {\n",
    "            'time': current_time,\n",
    "            'popup': f\"{row['VESSNAME']} ({row['ICST_DESC']})\",\n",
    "            'icon': 'circle',\n",
    "            'iconstyle': {\n",
    "                'fillColor': get_fill_color(row['ICST_DESC']),\n",
    "                'color': get_outline_color(row['source']),\n",
    "                'fillOpacity': 0.9,\n",
    "                'stroke': 'true',\n",
    "                'radius': 5\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "    features.append(point_feature)\n",
    "\n",
    "timestamped_geojson = {\n",
    "    'type': 'FeatureCollection',\n",
    "    'features': features\n",
    "}\n",
    "\n",
    "TimestampedGeoJson(\n",
    "    timestamped_geojson,\n",
    "    transition_time=200,\n",
    "    period='PT1H',\n",
    "    duration='PT1H',\n",
    "    add_last_point=False,\n",
    "    loop=False,\n",
    "    auto_play=False,\n",
    "    date_options='YYYY-MM-DD HH:mm',\n",
    "    time_slider_drag_update=True\n",
    ").add_to(m)\n",
    "\n",
    "# --- Legend ---\n",
    "legend_html = \"\"\"\n",
    "<div style=\"position: fixed; top: 10px; right: 10px; z-index: 9999; background-color: white;\n",
    "    padding: 10px; border: 2px solid #ccc; border-radius: 8px; box-shadow: 2px 2px 6px rgba(0,0,0,0.3);\n",
    "    font-size: 14px;\">\n",
    "<b>Ship Type Groups</b><br>\n",
    "<div style=\"margin-top: 5px;\">\n",
    "  <div><span style=\"background-color:#1f77b4;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>Container</div>\n",
    "  <div><span style=\"background-color:#ff7f0e;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>Tanker</div>\n",
    "  <div><span style=\"background-color:#2ca02c;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>Bulk Carrier</div>\n",
    "  <div><span style=\"background-color:#d62728;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>General Cargo</div>\n",
    "  <div><span style=\"background-color:#9467bd;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>RoRo</div>\n",
    "  <div><span style=\"background-color:#e377c2;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>Passenger / Cruise</div>\n",
    "  <div><span style=\"background-color:#8c564b;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>Barges & Support</div>\n",
    "  <div><span style=\"background-color:#7f7f7f;width:12px;height:12px;display:inline-block;margin-right:5px;\"></span>Specialized / Other</div>\n",
    "</div>\n",
    "</div>\n",
    "\"\"\"\n",
    "m.get_root().html.add_child(folium.Element(legend_html))\n",
    "\n",
    "m.save(\"combined_interactive_ship_movements_routed.html\")\n",
    "print(\"✅ Map saved as 'combined_interactive_ship_movements_routed.html'\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
