[data_sources]
us_domestics_csv = "https://sistemaupr.sharepoint.com/:x:/s/CETL-ObservatoriodeDatos/IQCN66cCP8vATrh3LmAvZqF6AUDedwOuK9ABlsUI52Hc2Wc?download=1"
international_xlsx = "https://sistemaupr.sharepoint.com/:x:/s/CETL-ObservatoriodeDatos/IQBhU17Vpm-vTYQE8qjXCHiAAWlDmqDKQchyV_VfI22xRBE?download=1"
