[data_sources]
us_domestics_csv = "https://sistemaupr.sharepoint.com/:x:/r/sites/CETL-ObservatoriodeDatos/Shared%20Documents/Visualizations/Dashboard%20Code/U.S%20Domestics%20Trade%20-%20Imports%20and%20Exports.csv?download=1"
international_xlsx = "https://sistemaupr.sharepoint.com/:x:/r/sites/CETL-ObservatoriodeDatos/Shared%20Documents/Visualizations/Dashboard%20Code/U.S%20International%20Trade%20-%20Imports%20and%20Exports.xlsx?download=1"

[passwords]
admin = "Ce2025tl"
user1 = "Cole2025gio"
